<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts">
	import SVGComponent from '../SVGComponent.svelte';
	import { createLazyComponentMotion as createComponentMotion } from '../lazy-component-motion.svelte.js';
	import type { MotionSVGElementProps } from './types.js';
	let { ref = $bindable(), ...attributes }: MotionSVGElementProps<'feTile'> = $props();
</script>

<SVGComponent tag="feTile" createBinding={createComponentMotion} {...attributes} bind:ref />
