<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts" generics="Type extends HTMLInputTypeAttribute | null = 'text'">
	import type { HTMLInputTypeAttribute } from 'svelte/elements';
	import type { MotionInputProps } from './types.js';
	import InputCheckbox from './InputCheckbox.svelte';
	import InputFile from './InputFile.svelte';
	import InputRadio from './InputRadio.svelte';
	import InputValue from './InputValue.svelte';
	let {
		type = 'text' as Type,
		value = $bindable(),
		checked = $bindable(),
		indeterminate = $bindable(),
		files = $bindable(),
		ref = $bindable(),
		...attributes
	}: MotionInputProps<Type> = $props();
</script>

{#if type === 'checkbox'}
	<InputCheckbox {...attributes} {value} bind:checked bind:indeterminate bind:ref />
{:else if type === 'file'}
	<InputFile {...attributes} bind:files bind:ref />
{:else if type === 'radio'}
	<InputRadio {...attributes} {value} {checked} bind:ref />
{:else}
	<InputValue {...attributes} {type} bind:value bind:ref />
{/if}
