<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts" generics="Value = unknown">
	import { createLazyComponentMotion as createComponentMotion } from '../lazy-component-motion.svelte.js';
	import { componentMotionOptions, nativeComponentProps } from '../component-props.js';
	import MotionChildren from '../MotionChildren.svelte';
	import type { MotionSelectProps } from './types.js';
	let {
		motion = {},
		ref = $bindable(),
		style,
		children,
		value = $bindable(),
		...attributes
	}: MotionSelectProps<Value> = $props();
	const binding = createComponentMotion(() => componentMotionOptions(motion, attributes, style));
	const nativeAttributes = $derived(nativeComponentProps(attributes));
	const motionTransition = binding.transition;
	function forwardRef(node: HTMLElement) {
		ref = node as HTMLElementTagNameMap['select'];
		return () => {
			if (ref === node) ref = null;
		};
	}
</script>

<select
	{...nativeAttributes}
	{...binding.props}
	style={`${typeof style === 'string' ? style : ''};${binding.props.style}`}
	transition:motionTransition|global
	{@attach forwardRef}
	multiple
	bind:value
>
	<MotionChildren {children} />
</select>
