<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts" generics="Value = unknown">
	import type { MotionSelectProps } from './types.js';
	import SelectSingle from './SelectSingle.svelte';
	import SelectMultiple from './SelectMultiple.svelte';
	let {
		multiple,
		value = $bindable(),
		ref = $bindable(),
		...attributes
	}: MotionSelectProps<Value> = $props();
</script>

{#if multiple}
	<SelectMultiple {...attributes} bind:value bind:ref />
{:else}
	<SelectSingle {...attributes} bind:value bind:ref />
{/if}
