<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts">
	import AmbiguousMotion from '../AmbiguousMotion.svelte';
	import { createLazyComponentMotion as createComponentMotion } from '../lazy-component-motion.svelte.js';
	import type { MotionAmbiguousElementProps } from './types.js';
	let { ref = $bindable(), ...attributes }: MotionAmbiguousElementProps<'style'> = $props();
</script>

<AmbiguousMotion tag="style" createBinding={createComponentMotion} {...attributes} bind:ref />
