<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts">
	import { createComponentMotion } from '../component-motion.js';
	import { componentMotionOptions, nativeComponentProps } from '../component-props.js';
	import type { MotionElementProps } from './types.js';
	let {
		motion = {},
		ref = $bindable(),
		style,
		children,
		...attributes
	}: MotionElementProps<'dfn'> = $props();
	const binding = createComponentMotion(() => componentMotionOptions(motion, attributes, style));
	const nativeAttributes = $derived(nativeComponentProps(attributes));
	const motionTransition = binding.transition;
	function forwardRef(node: HTMLElement) {
		ref = node as HTMLElementTagNameMap['dfn'];
		return () => {
			if (ref === node) ref = null;
		};
	}
</script>

<dfn
	{...nativeAttributes}
	{...binding.props}
	style={`${typeof style === 'string' ? style : ''};${binding.props.style}`}
	transition:motionTransition|global
	{@attach forwardRef}
>
	{@render children?.()}
</dfn>
