<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts">
	import SVGComponent from '../SVGComponent.svelte';
	import { createComponentMotion } from '../component-motion.js';
	import type { MotionSVGElementProps } from './types.js';
	let { ref = $bindable(), ...attributes }: MotionSVGElementProps<'feConvolveMatrix'> = $props();
</script>

<SVGComponent
	tag="feConvolveMatrix"
	createBinding={createComponentMotion}
	{...attributes}
	bind:ref
/>
