<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts">
	import { createComponentMotion } from '../component-motion.js';
	import type { MotionElementProps } from './types.js';
	let { motion = {}, ref = $bindable(), style, ...attributes }: MotionElementProps<'hr'> = $props();
	const binding = createComponentMotion(() => motion);
	const motionTransition = binding.transition;
	function forwardRef(node: HTMLElement) {
		ref = node as HTMLElementTagNameMap['hr'];
		return () => {
			if (ref === node) ref = null;
		};
	}
</script>

<hr
	{...attributes}
	{...binding.props}
	style={`${style ?? ''};${binding.props.style}`}
	transition:motionTransition|global
	{@attach forwardRef}
/>
