<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts">
	import { createComponentMotion } from '../component-motion.js';
	import type { NativeInputProps } from './types.js';
	let {
		motion = {},
		ref = $bindable(),
		style,
		type,
		value = $bindable(),
		...attributes
	}: NativeInputProps = $props();
	const binding = createComponentMotion(() => motion);
	const motionTransition = binding.transition;
	function forwardRef(node: HTMLElement) {
		ref = node as HTMLElementTagNameMap['input'];
		return () => {
			if (ref === node) ref = null;
		};
	}
</script>

<input
	{...attributes}
	{...binding.props}
	style={`${style ?? ''};${binding.props.style}`}
	transition:motionTransition|global
	{@attach forwardRef}
	{type}
	bind:value
/>
