<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts">
	import { createComponentMotion } from '../component-motion.js';
	import type { MotionElementProps } from './types.js';
	let {
		motion = {},
		ref = $bindable(),
		style,
		children,
		...attributes
	}: MotionElementProps<'ol'> = $props();
	const binding = createComponentMotion(() => motion);
	const motionTransition = binding.transition;
	function forwardRef(node: HTMLElement) {
		ref = node as HTMLElementTagNameMap['ol'];
		return () => {
			if (ref === node) ref = null;
		};
	}
</script>

<ol
	{...attributes}
	{...binding.props}
	style={`${style ?? ''};${binding.props.style}`}
	transition:motionTransition|global
	{@attach forwardRef}
>
	{@render children?.()}
</ol>
