<!-- Generated by scripts/generate-motion-elements.mjs. Edit the generator. -->
<script lang="ts" generics="Value = unknown">
	import { createComponentMotion } from '../component-motion.js';
	import type { MotionSelectProps } from './types.js';
	let {
		motion = {},
		ref = $bindable(),
		style,
		children,
		value = $bindable(),
		...attributes
	}: MotionSelectProps<Value> = $props();
	const binding = createComponentMotion(() => motion);
	const motionTransition = binding.transition;
	function forwardRef(node: HTMLElement) {
		ref = node as HTMLElementTagNameMap['select'];
		return () => {
			if (ref === node) ref = null;
		};
	}
</script>

<select
	{...attributes}
	{...binding.props}
	style={`${style ?? ''};${binding.props.style}`}
	transition:motionTransition|global
	{@attach forwardRef}
	bind:value
>
	{@render children?.()}
</select>
